### ISSUE TITLE
Logging the statement was successfully executed or not?

### ISSUE THREAD

**Issue by japinli** [pgaudit/pgaudit#106]
Hi,

I'm  curious are there any way to include a flag to identify whether the statement was successfully executed or not in pgAudit?

Best regards,
Japin Li

**Comment by dwsteele** [comment]
No, but you can check for errors within the same transaction (by logging the transaction id) to determine if the statement succeeded or not.

This isn't done in pgAudit because it would require holding transactions until we know they are successful which would negate the primary mission of logging statements as soon as possible -- it could also potentially use enough memory to cause problems for the postgres server.

**Comment by japinli** [comment]
@dwsteele Thanks for your advice.
