### ISSUE TITLE
Object Level Logging: WRITE operations logged when table has only SELECT permissions

### ISSUE THREAD

**Issue by pdonnelly** [pgaudit/pgaudit#126]
This might be more a documentation issue, but I'm finding when I grant the role specified by pgaudit.role only SELECT on a specific table, I wind up getting UPDATEs and DELETEs if those queries had a WHERE clause on the same table.

For example:

> CREATE ROLE auditor;
> SET pgaudit.log=none;
> SET pgaudit.role=auditor;
> GRANT SELECT ON TABLE mytable TO auditor;
> UPDATE mytable SET col1='value' WHERE id=1;

I'm finding this logs an UPDATE statement in the logs even though I haven't granted the pgaudit role UPDATE. I'm guessing this is because it is doing a SELECT on the table to find the proper row to update? I can confirm if I revoke the select permission, nothing is logged for either updates or selects on that table. Same thing happens with DELETEs if I do a `DELETE FROM mytable where id=1;` And finally, if I do a `UPDATE mytable SET col1='value'` without the WHERE, it does not log the UPDATE.

This behavior surprised me and took me a while to figure out what was going on. I would have assumed no UPDATEs or DELETEs would be logged unless I gave the role that specific permission, even if there were selects being used "behind the scenes". If this is intended behavior I get it, might just be nice to document that a little more in the object-level logging examples?

**Comment by sfrost** [comment]
Yes, an UPDATE or DELETE with a WHERE clause requires the user to have SELECT rights on the table and that's why pgaudit is logging those actions.  Were you to remove the user's SELECT rights from the table, an UPDATE or DELETE with a WHERE clause would fail with a permission denied error.  I agree that this may seem a bit odd, but doing an UPDATE with a WHERE results in the user being able to make inferences about what data exists in the table, which is why PG requires that user to have SELECT rights and pgaudit is simply picking up on that permissions check.  I don't think it'd really make sense to change this, and PG does document this: https://www.postgresql.org/docs/current/sql-update.html  I'm not sure that we need to add documentation about this explicitly in pgaudit...  Did you have a specific proposal though for what you'd like to see by way of a documentation improvement for pgaudit..?

**Comment by pdonnelly** [comment]
That all makes sense but wasn't clear immediately. Especially since setting "pgaudit.log=read" does not seem to log the UPDATE and DELETE statements when specifying WHERE clauses, only on the object level logging. 

As for updates to the pgaudit documentation, I was thinking of just adding an example to the existing one (that logs SELECT and DELETE) to show this example, perhaps with a link to the postgresql documentation you linked to above to explain why this is the happens.

Something like `update account set description = 'yada, yada' where id=1` which would show an UPDATE log message even though it isn't explicitly granted that permission. Hopefully it will save someone else coming in later from making the same assumption I made! 

Thanks for clarifying, I appreciate it.

**Comment by dwsteele** [comment]
@pdonnelly Please submit documentation changes as a PR if you would like us to consider them. Modifying the documentation, especially examples, is tricky because it can invalidate other parts of the docs.

**Comment by rayjasson98** [comment]
> Hopefully it will save someone else coming in later from making the same assumption I made!

Thanks for raising this. I couldn't understand why pgAudit logs the `UPDATE` statement when only `SELECT` privilege is granted on the tables... until I saw this.
