### ISSUE TITLE
The value in the COMMAND column of session audit log is not "COPY" after executed copy command.

### ISSUE THREAD

**Issue by ChenJiaoqian** [pgaudit/pgaudit#128]
Hello, when I use pgaudit to output the session audit log, I encountered the following problem:
step-1: set pgaudit.log='read, write';
step-2: set pgaudit.log_relation=on;
step-3: copy tb01 to '/home/postgres/data.txt';
AUDIT: SESSION,1,1,READ,SELECT,TABLE,public.tb01,…
step-4: copy tb01 from '/home/postgres/data.txt';
AUDIT: SESSION,2,1,WRITE,INSERT,TABLE,public.tb01,…

I think the COMMAND column should be "COPY". In fact, step-3 is "SELECT", step-4 is "INSERT".

But when pgaudit.log_relation is off, "COPY" is outputted.
step-2: set pgaudit.log_relation=off;
step-3: copy tb01 to '/home/postgres/data.txt';
AUDIT: SESSION,3,1,READ,COPY,…
step-4: copy tb01 from '/home/postgres/data.txt';
AUDIT: SESSION,4,1,WRITE,COPY,…

**Comment by dwsteele** [comment]
It is not clear to me that this is better. The data is being selected from the table when it is copied to a file. The copy is really on the file side which we do not audit.

Doing this would mean that users would need to search for both INSERT and COPY when looking for inserts into a table. Just looking for WRITE is not enough since that covers UPDATE as well. Likewise, SELECT and COPY would be needed on the READ side.

Is knowing the inserts came from a copy important enough to make the logs harder to query? I don't think so, but I would welcome input from @jconway or @sfrost.

**Comment by sfrost** [comment]
I agree that this doesn't really make sense to change- it's a SELECT or INSERT according to the table that's being audited, so the existing approach makes more sense.

**Comment by dwsteele** [comment]
Neither @sfrost nor I think this change is correct. No comment from @ChenJiaoqian or @JiangGuiqing so closing this issue and the associated PR.
