### ISSUE TITLE
Auditing users and specific commands

### ISSUE THREAD

**Issue by SamuelMolling** [pgaudit/pgaudit#158]
Hello, I have doubts if the behavior of pgaudit is correct, the idea was to audit commands from users who have the role DBA, only write and ddl commands, follow the settings:

pgaudit.log = 'write,ddl'
pgaudit.log_catalog = 'OFF'
pgaudit.log_client = 'OFF'
pgaudit.role = 'dba'

But by the looks of it, it returns in the log reads and all users, i would not like to audit the user postgres, for example

2021-09-13 19:30:06.127 UTC [8288] [postgres, postgres] LOG:  AUDIT: OBJECT,1,1,READ,SELECT,TABLE,public.backup_control,"update backup_control set status = 1 , backup_end = now() where id = (select id from backup_control order by id desc limit 1);",<not logged>

User/role :
samuel.molling      |                                                            | {dba}
 dba                 | Superuser                                                  | {}

**Comment by SamuelMolling** [comment]
Hello, I saw that we have how to audit a specific user giving `alter role USER set pgaudit.log='ddl,write';` , but I would like to know if I can change the role of a group and the audits will be done with the same of these groups, in the example above I went to the "dba" role and my user is part of this role, but there are X users also inside.

**Comment by SamuelMolling** [comment]
@dwsteele can you help me?

**Comment by dwsteele** [comment]
This is not how object auditing works. The role is used to define what will be audited, not who will be audited. See https://github.com/pgaudit/pgaudit#object-audit-logging for examples.

If you want specific audit settings for a user, they must be set with `alter user set` because GUCs are not inherited in the roles system. This is a limitation of how postgres works.
