### ISSUE TITLE
pgAudit on  Failure events

### ISSUE THREAD

**Issue by dimv36** [pgaudit/pgaudit#21]
Hello,

Thanks for your work! In our project we need to control all failure events (denying access and so on). So, pgaudit extension can register only success events. 

So, the question is: it is possible to add support for audit of failure events?

**Comment by dwsteele** [comment]
pgAudit cannot directly audit failure events since there are no appropriate hooks and in any case it would not be a good idea to hijack failures to attempt logging.

However, PostgreSQL already logs failures when `log_statements = all` and the `pgaudit_analyze` tool can use this information to determine which transactions (and thus which statements) have failed.  See the `pgaudit.audit_statement` table (https://github.com/pgaudit/pgaudit_analyze/blob/master/sql/audit.sql#L150).
