### ISSUE TITLE
pgaudit across multiple databases - separate instances needed?

### ISSUE THREAD

**Issue by chrislungu** [pgaudit/pgaudit#242]
morning,

I'm trying to understand if one installation of pgaudit per server is enough. I installed it in the default database "postgres" and set it up according to my needs. it seems to work properly across multiple databases, unless I'm missing anything obvious.

having said that, I've been advised on dba stack exchange that the extension must be installed in each database you're planning to audit, which seems excessive. having tested it myself, I can't see why, but I'd rather take advice from the people who wrote it.

is the default installation in postgres enough to audit the entire server or is the extension designed to be installed in each database that needs auditing?

thank you!

**Comment by dwsteele** [comment]
Most auditing features will work without the extension installed in the database you want to audit, but you will be missing information for DDL statements since that relies on database-level event triggers that are installed by the extension script. 

You can test this by creating a table in a database with the extension installed vs not. The audit records in the database without auditing will be missing the table schema/name.

**Comment by chrislungu** [comment]
very helpful, thank you!
