### ISSUE TITLE
How can I write audit logs to a different file and no longer pollute the server log?

### ISSUE THREAD

**Issue by lony** [pgaudit/pgaudit#63]
Refering to Ians email from [here](https://www.postgresql.org/message-id/5363390F.8040704@2ndquadrant.com)

> 1. Additional logging facilities, including to a separate audit
>     log file and to syslog, and potentially logging to a table
>     (possibly via a bgworker process). Currently output is simply
>     emitted to the server log via ereport().

How can I write audit logs to a different file and no longer pollute the server log? Could you add a section (possible or not) to the documentation, as this is a major feature.

**Comment by dwsteele** [comment]
PostgreSQL can be configured to send logs to syslog and from there you can use a variety of tools (Splunk, ELK, etc.) to manipulate the logs.

We don't have any plans to build special logging facilities into pgAudit.  Those enhancements would belong in core Postgres, if anywhere, but there's currently no consensus on what that would look like.

**Comment by lony** [comment]
@dwsteele by any chance do you know if there is an open issue for that at PostgreSQL where you could point me to? I think its a needed feature and would elsewise open it.

**Comment by dwsteele** [comment]
Not to my knowledge.  It has been discussed informally among the hackers at conferences and such but no patch has been proposed.  You are, of course, welcome to do so yourself.

**Comment by lony** [comment]
Thanks

**Comment by johanot** [comment]
I know this issue is old, sorry....

On high-traffic clusters, we spend a significant amount of cycles post-filtering postgres log messages from audit log messages. It's not an impossible task, however I just wish we could simply ingest the pgaudit events from a separate file descriptor. This would give us more flexibility in prioritizing/scheduling the processing queues for different types of events.

Please excuse my lack of extension-dev knowlegde: I don't know how much of an extension-anti-pattern it would be for pgaudit to optionally open its own output fd?

**Comment by jankatins** [comment]
@rdunklau has some knowledge about log related stuff in pg core

**Comment by rdunklau** [comment]
We don't have a built in mechanism to redirect specific log messages to specific output. I proposed to add tags to the log infrastructure, to make it easier to filter messages: https://commitfest.postgresql.org/36/3293/

I need to work on this as it doesn't work on windows yet, but hopefully that would be a good start to add log dispatcher in another extension, rather than hardcoding log handling in any extension that want to use that.

**Comment by dwsteele** [comment]
Adding any kind of reasonable logging infrastructure to pgAudit would be a very large task and log aggregation would be incredibly hard to implement separately, so each backend would produce a separate log. We've looked at it before and it is simply not practical or a good use of our time.

Improvements to PostgreSQL logging are the way to go here.
